# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유현지
title: Backend Developer
email: yoo77hyeon@gmail.com
website: https://hamcheeseburger.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  hamcheeseburger
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: 현지-유-77558b258
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-globe
  url: https://hamcheeseburger.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  3년차 백엔드 개발자로 일하고 있으며, 
  문제해결을 위해 기술적으로 깊게 파고드는 부분은 물론이고, 근본적인 원인 해결을 위해 컨텍스트를 파악하는 개발자가 되기 위해 노력하고 있습니다.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우아한형제들
        link: https://www.woowahan.com/
        # link_text: boringcompany.com
        sub_title: 내/외부 중계 서버 개발
        caption: 2023 1월 - 현재
        quote: >
          MAU 1500만, 일 ~의 트래픽
        description: | # this will include new lines to allow paragraphs
          - 다양한 주문스펙을 하나의 통일된 스펙으로 중계할 수 있는 내부 서비스 개발
          - 외부 배달대행사/포스사와 연동하는 서비스 개발
          - 대량 트래픽에서의 API/Worker/Batch 서버 개발

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 주문중계 플랫폼 서비스 개발
#        link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title: sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          다양한 주문스펙을 하나로 통합하여 중계할 수 있는 플랫폼 서비스 초기 개발 및 유지보수
        description: | # this will include new lines to allow paragraphs
          **기술 스택**
          - Java, Springboot, Kafka, MySql, Ngrinder
          
          **주요 작업**
          - sdk를 제공하여 소비처에서 원하는 페이로드 형태로 수신할 수 있도록 함
          - 기존 flow의 처리 속도 비교와 페이로드 스펙을 검증할 수 있는 서버 개발
#          - (TBD) 퍼포먼스 및 비용절감 측면에서 작성 필요
      - layout: top-middle
        title: 배민주문접수PC Lite 서버 개발
        quote: >
          업주가 POS 디바이스에서 배민주문을 접수할 수 있는 프로그램 서버 개발
        description: | # this will include new lines to allow paragraphs
          **기술 스택**
          - Kotlin, Java, WebFlux, Springboot, MySql, Redis, Ngrinder
          
          **주요 작업** 
          - MAU 3800 트래픽을 받아내는 시스템 초기 구축 및 개발
          - Webflux 기반 BFF 서버 개발 및 여러 백엔드 API 병렬 호출을 통한 네트워크 효율성 향상
          - Ngrinder를 통한 성능측정 및 최적화
          
#          ** 성과 **
#          - 포스사와의 공식연동으로 비공식적 후킹사례 15% 감소

      - layout: top-middle
        title: 시스템 안정성 향상을 위한 개발
        description: | # this will include new lines to allow paragraphs
          - 이벤트 처리기 장애 시, 주문팀과의 상태 동기화를 위한 batch 서버 개발
          - 비인가 외부업체 후킹 방지를 위한 API 보안 개발 
          - 외부중계 주문이벤트 재발행 시스템 구성
      - layout: top-middle
        title: 생산성 향상을 위한 개발
        #        quote: >
        #          업주가 POS 디바이스에서 배민주문을 접수할 수 있는 프로그램 서버 개발
        description: | # this will include new lines to allow paragraphs
          - 모니터링 대시보드 구축 및 관리시스템 통합
          - 불필요한 인프라 리소스 제거로 인한 비용절감

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우아한테크코스
        caption: 2022.02 - 2022.11
        sub_title: 백엔드 개발 교육 코스
#        quote: >

        description: | # this will include new lines to allow paragraphs
          - Java와 객체지향설계에 대한 학습
          - TDD를 통해 구현하는 방법 학습
          - Spring boot와 JPA에 대한 학습
          - 팀프로젝트를 통한 협업 경험
          - 글쓰기 연습을 통한 소프트스킬 향상

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
